import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';

/**
 * One flat config for the whole monorepo.
 *
 * Per-workspace configs were the obvious alternative, but three of them would
 * drift apart — and the api workspace had a `lint` script with no config at all,
 * so `npm run lint` failed at the root and nobody noticed. A single config that
 * CI can run in one command is harder to leave broken.
 *
 * Type-aware rules are deliberately not enabled: they need a TypeScript program
 * per workspace and turn a two-second check into a minute-long one, which is how
 * linting quietly stops being run.
 */
export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      '**/coverage/**',
      'prisma/migrations/**',
      // Generated by Next on every build; not ours to satisfy.
      'apps/web/next-env.d.ts',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    files: ['**/*.{ts,tsx,mts,mjs,js}'],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: 'module',
      globals: { ...globals.node },
    },
    rules: {
      // The base rule misfires on TypeScript overloads and enum declarations;
      // the TS-aware version is the one that should speak.
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      // `any` is a signal, not a crime — it should slow an author down without
      // failing a build that is otherwise sound.
      '@typescript-eslint/no-explicit-any': 'warn',
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      eqeqeq: ['error', 'smart'],
      'prefer-const': 'error',
    },
  },

  // Scripts that drive a browser. The bodies of `page.evaluate` callbacks are
  // serialised and run in the page, so `document` and `window` are legitimate
  // there even though the file itself runs under Node — and a script whose
  // whole job is to report progress needs to print it.
  {
    files: ['scripts/**/*.mjs'],
    languageOptions: { globals: { ...globals.node, ...globals.browser } },
    rules: { 'no-console': 'off' },
  },

  // Browser code.
  {
    files: ['apps/web/**/*.{ts,tsx}'],
    languageOptions: { globals: { ...globals.browser, ...globals.node } },
  },

  // Nest DTOs declare validated shapes with no initialiser and decorators do the
  // rest; the empty-class rule reads PartialType subclasses as pointless.
  {
    files: ['apps/api/src/**/dto.ts'],
    rules: { '@typescript-eslint/no-extraneous-class': 'off' },
  },

  // Tests and scripts.
  {
    files: ['**/*.spec.ts', '**/*.test.ts'],
    languageOptions: { globals: { ...globals.jest, ...globals.node } },
  },
  {
    files: ['prisma/seed.mjs', '*.config.mjs', '*.config.ts'],
    rules: { 'no-console': 'off' },
  },
);
